# Generated by Django 2.0.2 on 2018-02-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20180219_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.FileField(upload_to='personal/'),
        ),
    ]
