# Generated by Django 2.0.2 on 2018-02-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20180219_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.IntegerField(default=-1, unique=True),
            preserve_default=False,
        ),
    ]
