# Generated by Django 2.0.2 on 2018-02-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_project_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='position',
            field=models.IntegerField(),
        ),
    ]
