# Generated by Django 2.0.2 on 2018-02-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20180219_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.FileField(blank=True, upload_to='personal/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='position',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
